### ISSUE TITLE
Optional & prefix CLI arguments

### ISSUE THREAD

**Issue by vitorqb** [vitorqb/sazed#23]
Add two argument to memory placeholders: `optional` and `prefix`. Like this:

```yaml
- command: grep {{f-exclude-dir}} {{searchable}} {{path}}
  description: Generic grep
  arguments:
    grep:
      f-exclude-dir:
        optional: true
        prefix: "--exclude-dir="
      path:
        optional: true
```

This means:

(1)
The user may or may not specify a value for `f-exclude-dir`.

(1.a)
If they do, the rendered Memory must include `--exclude-dir=...`, where `...` is the user input. For example, if the user input `foo`, the rendered command must include `--exclude-dir=foo`.

(1.b)
If they do NOT, the rendered Memory must no include anything (not even a space). In the example above, if `searchable=foo` and `path=bar`, it should render `grep foo bar`.
